development:
 adapter: postgresql
 encoding: unicode
 database: lumarylove_development
 pool: 5

test:
 adapter: postgresql
 encoding: unicode
 database: lumarylove_test
 pool: 5

production:
 adapter: postgresql
 encoding: unicode
 database: lumarylove_production
 pool: 5